services:
  db:
    image: postgres:14
    container_name: value-index-db
    env_file:
      - ../.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=price_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d price_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - value-index-net

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: value-index-app
    env_file:
      - ../.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=price_tracker
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FILE=${LOG_FILE}
      - BESTBUY_API_KEY=${BESTBUY_API_KEY}
      - BESTBUY_BASE_URL=${BESTBUY_BASE_URL}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../logs:/app/logs
    restart: always
    healthcheck:
      test: ["CMD", "bun", "run", "scripts/health-check.ts"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - value-index-net

networks:
  value-index-net:
    name: value-index-net

volumes:
  postgres_data:
    name: value-index-db-data